// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RecordsMaster.Data;

#nullable disable

namespace RecordsMaster.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421092806_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");
#pragma warning restore 612, 618
        }
    }
}